version: '3'

services:
  php-fpm:
    container_name: php-fpm-dev
    build:
      context: .
      dockerfile: df-php.dockerfile
    tty: true
    volumes:
      - ./php/app:/usr/src/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/log:/var/log

  nginx:
    container_name: nginx-dev
    build:
      context: .
      dockerfile: df-nginx.dockerfile
    depends_on:
      - php-fpm
    tty: true
    volumes:
      - ./php/app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 10902:80
